services:
  psql_db:
    image: postgres:13.4
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - PGDATA=/pgdata
    volumes:
      - psql_db-data:/pgdata
    ports:
      - "5429:5432"


volumes:
  psql_db-data: